spring:
  application:
    name: ChatMemory

  port: 8080
  ai:
    openai:
      api-key: ${NVIDIA_API_KEY}
      base-url: https://integrate.api.nvidia.com/v1
      chat:
        options:
          model: nvidia/nemotron-3.5-lightning-30b-a3b
          max-tokens: 300

        extra-body:
          chat_template_kwargs:
            enable_thinking: false
