spring.application.name=ToolCalling

#AI-CONFIGURATION
spring.ai.openai.api-key=${NVIDIA_API_KEY}
spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
spring.ai.openai.chat.options.model=nvidia/nemotron-3.5-lightning-30b-a3b
spring.ai.openai.chat.options.max-tokens=1000
spring.ai.model.embedding=none
logging.level.org.springframework.ai.chat.client.advisor=DEBUG