spring.application.name=First-Project
server.port=8081

spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.options.model=minimax/minimax-m3:free
spring.ai.openai.chat.options.max-tokens=2048
spring.ai.model.embedding=none


# Disable unwanted Spring-AI auto configuration
#spring.ai.model.audio.transcription=none
#spring.ai.model.audio.speech=none
#spring.ai.model.chat=none
#spring.ai.model.image=none
#spring.ai.model.embedding=none
#spring.ai.chat.client.enabled=false
#spring.ai.model.moderation=none
