spring.application.name=DockerModelRunner

# Docker Model Runner
spring.ai.openai.base-url=http://localhost:12434/engines/v1
spring.ai.openai.api-key=docker
spring.ai.openai.chat.model=ai/smollm3

# Disable OpenAI audio speech auto-configuration
spring.ai.model.audio.speech=none